### ISSUE TITLE
Unexpected number error

### ISSUE THREAD

**Issue by shuyue426** [bytedance/magic-portal#2]
While try use in local like:
<magic-portal src="http://localhost:xx"

It throws VM12698:1 Uncaught (in promise) SyntaxError: Unexpected number
    at eval (&ltanonymous>)
    at evalWithEnv (index.esm.js:1018)
    at Sandbox.execScript (index.esm.js:3988)

At execute (0, eval)(internalizeString);

And the internalizestring seems magic's code as: ;(function(0,1,2,3,4,5,6,window){/*
 * ATTENTION: The "eval" devtool has been used (maybe by default in mode: "development").
 * This devtool is neither made for production nor for readable output files.
 * It uses "eval()" calls to create a separate source file in the browser devtools.
 * If you are trying to read the output file, select a different devtool (https://webpack.js.org/configuration/devtool/)
 * or disable the default devtool with "devtool: false".
 * If you are looking for production-ready output files, see mode: "production" (https://webpack.js.org/configuration/mode/).
 */
/******/ (() => { // webpackBootstrap
/******/ 	var __webpack_modules__ = ({

/***/ "./node_modules/@magic-microservices/magic/dist/index.esm.js":
/*!*******************************************************************!*\
  !*** ./node_modules/@magic-microservices/magic/dist/index.esm.js ***!
  \*******************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

**Comment by jijiaxin1808** [comment]
#3 
There are some error in our sandbox， we will fix them later

**Comment by h-a-n-a** [comment]
Bug is fixed in the latest version, you may check it out later! :)

**Comment by shuyue426** [comment]
Thanks,it work~
wish this project better.

**Comment by h-a-n-a** [comment]
> Thanks,it work~
> wish this project better.

Very glad to hear this from you, appreciated it! XD
