### ISSUE TITLE
Load react app all button events lose

### ISSUE THREAD

**Issue by shuyue426** [bytedance/magic-portal#6]
While load a react app,
all events bind to button lose function.
I am wondering whether caused  by Synthetic Event  of react 16.xx.xx?
Is there any idea or solution,thanks?

**Comment by h-a-n-a** [comment]
> While load a react app,
> 
> all events bind to button lose function.
> 
> I am wondering whether caused  by Synthetic Event  of react 16.xx.xx?
> 
> Is there any idea or solution,thanks?

React 16 failed to apply target on the rootNode, which is caused by shadow dom, you may try to use patch package retarget-events or upgrade to react 17 directly

**Comment by shuyue426** [comment]
> > While load a react app,
> > all events bind to button lose function.
> > I am wondering whether caused  by Synthetic Event  of react 16.xx.xx?
> > Is there any idea or solution,thanks?
> 
> React 16 failed to apply target on the rootNode, which is caused by shadow dom, you may try to use patch package retarget-events or upgrade to react 17 directly

Sure，upgrade to 17 solve it。
